# Generated by Django 5.0.3 on 2026-05-10 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_laboratorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.TextField(blank=True, null=True)),
                ('resuelto', models.BooleanField(blank=True, null=True)),
                ('id_lab', models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='laboratorio_laboratorio.laboratorio')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(blank=True, null=True)),
                ('id_actividad', models.ForeignKey(blank=True, db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='laboratorio_actividad.actividad')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'Tarea',
            },
        ),
        migrations.CreateModel(
            name='ActividadTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('id_activ', models.ForeignKey(blank=True, db_column='id_activ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_tareas', to='laboratorio_actividad.actividad')),
                ('id_tarea', models.ForeignKey(blank=True, db_column='id_tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_tareas', to='laboratorio_actividad.tarea')),
            ],
            options={
                'verbose_name': 'Actividad-Tarea',
                'verbose_name_plural': 'Actividad-Tareas',
                'db_table': 'ActividadTarea',
            },
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(blank=True, db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to='laboratorio_actividad.actividad')),
                ('id_lab', models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to='laboratorio_laboratorio.laboratorio')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Actividad',
                'verbose_name_plural': 'Usuario-Actividades',
                'db_table': 'UsuarioActividad',
            },
        ),
    ]
