# Generated by Django 6.0.3 on 2026-06-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_actividad', '0001_initial'),
        ('laboratorio_laboratorio', '0003_accesorio_laboratorio_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='id_accesorio',
            field=models.ForeignKey(blank=True, db_column='id_accesorio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='laboratorio_laboratorio.accesorio'),
        ),
    ]
