# Generated by Django 6.0.3 on 2026-04-05 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('capacidad', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.TextField(blank=True, null=True)),
                ('resuelto', models.BooleanField(blank=True, null=True)),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
                ('id_lab', models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_activo', models.IntegerField(blank=True, null=True)),
                ('id_lab', models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'Maquina',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificacion',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('id_aux', models.ForeignKey(blank=True, db_column='id_aux', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(blank=True, null=True)),
                ('id_actividad', models.ForeignKey(blank=True, db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='laboratorio.actividad')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'Tarea',
            },
        ),
        migrations.CreateModel(
            name='ActividadTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('id_activ', models.ForeignKey(blank=True, db_column='id_activ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_tareas', to='laboratorio.actividad')),
                ('id_tarea', models.ForeignKey(blank=True, db_column='id_tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_tareas', to='laboratorio.tarea')),
            ],
            options={
                'verbose_name': 'Actividad-Tarea',
                'verbose_name_plural': 'Actividad-Tareas',
                'db_table': 'ActividadTarea',
            },
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(blank=True, db_column='id_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to='laboratorio.actividad')),
                ('id_lab', models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to='laboratorio.laboratorio')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Actividad',
                'verbose_name_plural': 'Usuario-Actividades',
                'db_table': 'UsuarioActividad',
            },
        ),
    ]
