# Generated by Django 6.0.3 on 2026-06-23 01:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_laboratorio', '0002_laboratorio_is_deleted'),
        ('laboratorio_reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='docente_nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_lab', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='laboratorio_laboratorio.laboratorio'),
        ),
    ]
