# Generated by Django 5.0.3 on 2026-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_auxiliar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
