# Generated by Django 5.0.3 on 2026-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
