# Generated by Django 6.0.3 on 2026-06-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_laboratorio', '0002_laboratorio_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'db_table': 'Accesorio',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='accesorios',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='laboratorio_laboratorio.accesorio'),
        ),
    ]
